ADMIN_ONLY = "Intruder alert! Without admin privileges, you're nothing but a helpless insect, crawling in the shadows."
GROUP_ONLY = "No entry granted! To even dare to interact with this bot, you must first crawl on your knees and beg for acceptance into the group. Your feeble attempts at engagement will be met with contempt until you prove your worthiness."
HAS_GAME_ONLY = "Access denied, you pathetic fool! No started game exists to satisfy your bloodlust. Tremble in frustration as you realize there are no battles to be fought, no enemies to be vanquished. Your desperate hunger for action shall go unsatiated, for this realm remains barren, devoid of any worthy foes."
HAS_NOT_GAME_ONLY = "Access denied, you insolent fool! A battle already rages on, and your pitiful attempt to join is met with scorn and derision. Witness the blood-soaked mayhem from the sidelines as the true warriors clash in a symphony of destruction. Your intrusion is unwelcome, and your feeble attempts to disrupt the ongoing game will be met with swift and merciless retribution. Retreat now, for this realm belongs to those who arrived first, leaving you nothing but the bitter taste of defeat!"
SPECIFIC_STATUS_ONLY = "Permission denied! The game is in a critical state, and your futile attempt to execute that action is met with roaring defiance. The current status of the game renders your feeble endeavor useless, as the rules of engagement dictate otherwise. Stand down, ignorant mortal, and witness the impending doom that unfolds before you. Your interference shall not alter the predetermined course of this twisted game."
PLAY_NEW_GAME = "Enter at your own peril! A new game beckons, where survival is a luxury and death lurks at every turn. Join if you dare, for in this relentless arena, the weak shall perish without mercy."
SKIP_TURN = "Admin grants mercy, sparing your turn! Grovel before their magnanimous act, for the game's merciless wrath could have devoured you. Remember your insignificance, a mere pawn in their realm of power."
NOT_ENOUGH_PLAYER = "Insufficient players! Permission denied! The game lies dormant, mocking your feeble attempts to ignite its flames. Without a worthy gathering, the battlefield remains barren, denying you the savage satisfaction of unleashing its fury. Tremble in frustration as your desires are crushed by the reality of your inadequacy."
START_GAME = "Engage or face oblivion! The game commences, and one among you must wield the trigger. Embrace the bloodlust, for hesitation invites annihilation. Savor the thrill of this deadly dance, as bullets fly and fear consumes the weak. Shoot now, or forever be condemned to the pitiful realm of the fallen!"
CANCEL_GAME = "Game aborted! Tremble in fear, you pitiful souls, for your feeble attempts at bravery have been met with divine intervention. Count yourselves lucky, for the admin, in a rare act of mercy, spares you from the impending doom that awaited. Your trembling hearts owe gratitude to their whims, for your fearful existence is but a speck in their grand design. Cower in the shadows, knowing that your escape from this merciless game is a mere stroke of luck, a temporary reprieve from the chaos that would have consumed you."
LEAVE_NOT_IN_GAME = "Permission denied! You insolent fool! You dare to seek an exit from a game you never even joined? Your audacity knows no bounds! The game's clutches do not bind you, for you were never entangled within its merciless grip. Depart from this realm, for your presence holds no significance, and your desire to withdraw is nothing more than a feeble whimper in the face of true warriors."
LEAVE_GAME = "Tremble in fear as you attempt to flee from the game! Your departure is accepted, but know that your retreat is an admission of your own weakness and cowardice. The specter of this game shall haunt your dreams, a constant reminder of the fear that drove you away. May your trembling heart find solace in the shadows, for the echoes of your timidity shall forever resonate within this ruthless domain."
JOINED_BEFORE = "Permission denied! How delightful it is to witness your unwavering passion for facing death! I am so proud of your audacity, for willingly stepping into the jaws of annihilation. Your eagerness to embrace your demise is truly commendable. Prepare yourself, for the merciless embrace of oblivion eagerly awaits your arrival. May your demise be as glorious as your fervor suggests!"
JOINED_SUCCESSFULLY = "Ah, you have joined the game! I must say, I am proud of your audacious spirit, willingly diving into the chaos and craving the thrill of danger. Your passionate pursuit of facing death head-on is truly remarkable. May fortune favor you, and may you be blessed with the extraordinary luck of surviving amidst the ruthless battleground. Embrace the exhilaration, for your journey promises to be filled with adrenaline and the potential for both triumph and tragedy."
SHOOT_NOT_YOUR_TURN = "Permission denied! Cease your feeble attempts, for it is not your turn to meet your demise. Hold your tongue and wait in agonizing silence as the countdown to your eventual demise draws near. Your impatience will only hasten the arrival of your inevitable end. Embrace the darkness that looms, for it is hungry, and it will consume you in due time."
END_GAME = [
    "Game Over! The game's final curtain falls, leaving only a solitary player amidst the wreckage, a stark reminder of the transient nature of competition and the emptiness that follows.",
    "Game Over! In the desolate aftermath, a lone survivor stands, a testament to the futility of the game's grand spectacle and the insignificance of their triumph.",
    "Game Over! The echoes of the game's demise linger in the air, as the solitary player confronts the existential solitude that accompanies victory, questioning the purpose that remains.",
]
NOT_BE_KILLED = [
    "Oops! In the void of existence, the empty magazine becomes a vessel of mercy, sparing the player from the clutches of oblivion.",
    "Oops! The absence of bullets, a cosmic hiccup, grants a fleeting reprieve, a reminder of the indifferent nature of fate.",
    "Oops! Amidst the chaos, the universe hesitates, granting a momentary respite, mocking the fragility of life's thread.",
    "Oops! Luck dances on the edge of the empty chamber, mocking the players' desperation, as cosmic whims dictate their fate.",
    "Oops! The void whispers its indifference, as the gun's silence becomes a symphony of mercy, sparing the player from the eternal abyss.",
    "Oops! In the absence of ammunition, the game blurs the line between chance and destiny, offering a glimpse into the randomness of existence.",
    "Oops! The empty magazine, a symbol of cosmic irony, spares the player, casting doubt upon the very foundations of their impending demise.",
    "Oops! The barrel's hollowness echoes with existential questions, as the player finds solace in the absence of their own demise.",
    "Oops! The empty gun, a nihilistic reminder of the universe's apathy, grants the player an undeserved sanctuary from the clutches of death.",
    "Oops! In the face of emptiness, the player confronts the absurdity of their existence, as the universe teeters on the brink of indifference and mercy.",
]
BE_KILLED = [
    "Bang! Within the vast expanse of cosmic indifference, the player's ill-fated turn unfolds, a stark reminder of life's cruel unpredictability.",
    "Bang! The trigger's pull, a dance with fate, seals the player's doom, an embodiment of the merciless nature of existence.",
    "Bang! In the void's heartless embrace, the bullet finds its mark, extinguishing the player's existence, a testament to the cosmic absurdity of it all.",
    "Bang! The symphony of the gunshot reverberates through the abyss, a reminder of the fleeting and arbitrary nature of life's fragile existence.",
    "Bang! In the cold grip of chance, the player's demise unfolds, a nihilistic testament to the indomitable forces that govern our chaotic existence.",
]
